---
- name: "[debian]: logging hardening"
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: "{{ ansible_python_interpreter_system }}"

  tasks:
    - name: Ensure rsyslog and logrotate are present
      apt:
        name:
          - rsyslog
          - logrotate
        state: present
        update_cache: false

    - name: Ensure rsyslog is running and enabled
      service:
        name: rsyslog
        state: started
        enabled: true
