---
debian_netboot_catalog:
  - label: "Buster:10"
    version: "10"
    codename: "Buster"
    arch: "amd64"
    netinst_url: "https://cdimage.debian.org/cdimage/archive/10.13.0/amd64/iso-cd/debian-10.13.0-amd64-netinst.iso"
  - label: "Bullseye:11"
    version: "11"
    codename: "Bullseye"
    arch: "amd64"
    netinst_url: "https://cdimage.debian.org/cdimage/archive/11.7.0/amd64/iso-cd/debian-11.7.0-amd64-netinst.iso"
  - label: "Bookworm:12"
    version: "12"
    codename: "Bookworm"
    arch: "amd64"
    netinst_url: "https://cdimage.debian.org/cdimage/release/12.13.0/amd64/iso-cd/debian-12.13.0-amd64-netinst.iso"
  - label: "Trixie:13"
    version: "13"
    codename: "Trixie"
    arch: "amd64"
    netinst_url: "https://cdimage.debian.org/cdimage/release/13.4.0/amd64/iso-cd/debian-13.4.0-amd64-netinst.iso"
